IDENTIFICATION DIVISION.
       PROGRAM-ID. CHOICE.
DATA DIVISION.
       LINKAGE SECTION.
           01  LS-USERNAME        PIC X(20).
           01  LS-PASSWORD        PIC X(20).
           01  LS-RETURN-CODE     PIC X.

PROCEDURE DIVISION USING WS-MESSAGE, OUTPUT-RECORD, INPUT-FILE, WS-END-FILE, INPUT-RECORD, WS-CHOICE, MIN-VALUE-CHOICE, MAX-VALUE-CHOICE.
       MOVE "Enter your choice as a number:" TO WS-MESSAGE
       DISPLAY WS-MESSAGE
       MOVE WS-MESSAGE TO OUTPUT-RECORD
       WRITE OUTPUT-RECORD.

       READ INPUT-FILE
           AT END MOVE "Y" TO WS-END-FILE
           NOT AT END MOVE INPUT-RECORD TO WS-CHOICE
       END-READ

       PERFORM UNTIL (WS-CHOICE >= MIN-VALUE-CHOICE)
                      AND (WS-CHOICE <= MAX-VALUE-CHOICE)
           DISPLAY "Not a valid choice. Try again."

           READ INPUT-FILE
               AT END MOVE "Y" TO WS-END-FILE
               NOT AT END MOVE INPUT-RECORD TO WS-CHOICE
           END-READ
       END-PERFORM.

       GOBACK.